### ISSUE TITLE
Feature Request: Managed SQLserver as a resource.

### ISSUE THREAD

**Issue by lmicke** [yandex-cloud/terraform-provider-yandex#142]
Is the Terraform ressource for the managed SQLServer on the Roadmap. 

The Data Source was added in the last version. 

In our current project, the ManagedSQLServer is the only ressource we can't manage via terraform. 

Would just be nice too know, if we can plan with it in the near future. 

Thanks

**Comment by superbotan** [comment]
Hello! A Resource and DataSource are implemented for Sqlserver. However, an error was made in the file name for the documentation. 

Now the documentation is here https://github.com/yandex-cloud/terraform-provider-yandex/blob/master/website/docs/r/mdb_sqlserver_cluster.html.mdmarkdown

I'll write here when the bug is fixed

**Comment by victoriavoss96** [comment]
Thanks for the quick response

**Comment by superbotan** [comment]
Hello!
New documentation address: https://github.com/yandex-cloud/terraform-provider-yandex/blob/master/website/docs/r/mdb_sqlserver_cluster.html.markdown. I will write a comment here when the documentation is on the terraform website.

**Comment by apilikov** [comment]
Do you still experience troubles with the issue with the latest provider?

**Comment by victoriavoss96** [comment]
No, works perfectly. Issue can be closed.
