### ISSUE TITLE
PR #207 was reverted. What reason?

### ISSUE THREAD

**Issue by psmolkin** [yandex-cloud/terraform-provider-yandex#239]
I noticed the [PR#207](https://github.com/yandex-cloud/terraform-provider-yandex/pull/207) was reverted by this commit (https://github.com/yandex-cloud/terraform-provider-yandex/commit/0b1d61efd7c4e6fa7d232ff23f9c5f61a44bb644) from @apilikov without any messages.

I would like to know a reason and can I expect to see my changes in the repository again 🙄

**Comment by apilikov** [comment]
Hello! It is a legitimate question that you are asking :-), so the reason is that I accepted your code without tests. Thought I could write them myself but didn't find time and had to rollback your changes as we cannot accept new objects without tests. So, there are two possible options: you can submit new patch with acceptance test (not sure if you are familiar with it) or you can try waiting until I have done it myself. 😊

**Comment by psmolkin** [comment]
I've just recreated the patch https://github.com/yandex-cloud/terraform-provider-yandex/pull/242
